# Generated by Django 4.1.3 on 2022-12-05 22:21

import base_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_column='fecha_creacion', verbose_name='Fecha de creación')),
                ('rut', models.CharField(db_column='rut', max_length=30, unique=True, verbose_name='Rut')),
                ('nombre', models.CharField(db_column='nombre_contacto', max_length=200, verbose_name='Nombre Contacto')),
                ('razon_social', models.CharField(db_column='razon_social', max_length=200, verbose_name='Razón Social')),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(db_column='email', max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=25, null=True, verbose_name='Teléfono')),
                ('tipo_cliente', models.CharField(choices=[('micro', 'Micro Empresa'), ('pequeña', 'Empresa Pequeña'), ('mediana', 'Empresa Mediana'), ('grande', 'Empresa Grande')], db_column='tipo_cliente', max_length=50, verbose_name='Tipo de Cliente')),
                ('tipo_sistema', models.CharField(choices=[('SAP_CRM', 'SAP CRM'), ('SAP_CX', 'SAP CX'), ('SAP_SOLMAN', 'SAP SOLMAN'), ('HANA', 'HANA'), ('CPI', 'CPI'), ('PO', 'PO'), ('PI', 'PI')], db_column='tipo_sistema', max_length=50, verbose_name='Tipo de sistemas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre_documento_general', max_length=150, verbose_name='Nombre Documento')),
                ('descripcion', models.TextField(db_column='descripcion_doc', verbose_name='Descripción del Documento')),
                ('tipo', models.CharField(choices=[('new_Release', 'New Release'), ('upgrade_schedule', 'Upgrade Schedule'), ('instructivo_integraciones', 'Instructivo Integraciones'), ('manual_certificaciones', 'Manual Certificaciones'), ('presentaciones', 'Presentaciones'), ('conocimiento_general', 'Conocimiento General'), ('otros', 'Otros')], db_column='tipo_doc_general', max_length=150, verbose_name='Tipo de Documento')),
                ('documento', models.FileField(upload_to='general_documents/', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento General',
                'verbose_name_plural': 'Documentos Generales',
                'db_table': 'documento_general',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.TextField(db_column='recomendacion', verbose_name='Recomendación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.cliente')),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recomendacion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(db_column='nombre_documento', max_length=150, verbose_name='Nombre Documento')),
                ('descripcion_documento', models.TextField(db_column='descripcion_documento', verbose_name='Descripción del Documento')),
                ('tipo_documento', models.CharField(choices=[('contrato_soporte', 'Contrato Soporte'), ('CRM', 'Credenciales CRM'), ('ERP', 'Credenciales ERP'), ('SOLMAN', 'Credenciales SOLMAN'), ('CX', 'Credenciales CX'), ('CPI', 'Credenciales CPI'), ('restricciones', 'Restricciones'), ('estimacion_mejora', 'Estimación de Mejora'), ('factibilidad_mejora', 'Factibilidad de Mejora'), ('presentaciones', 'Presentaciones'), ('otros', 'Otros')], db_column='tipo_documento', max_length=100, verbose_name='Tipo de Documento')),
                ('documento', models.FileField(upload_to=base_app.models.document_upload_location, verbose_name='Documento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos Clientes',
                'db_table': 'documentos_clientes',
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='apellido', max_length=150, verbose_name='Apellido')),
                ('rut', models.CharField(db_column='rut', max_length=20, unique=True, verbose_name='Rut')),
                ('departamento', models.CharField(choices=[('solution_manager', 'Solution Manager'), ('CRM', 'CRM'), ('HANA', 'HANA'), ('customer_experience', 'Customer Experience')], db_column='departamento', max_length=60, verbose_name='Departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'db_table': 'consultor',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.consultor', verbose_name='Creado Por'),
        ),
    ]
