# Generated by Django 4.1.3 on 2023-01-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_consultor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentogeneral',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_app.consultor', verbose_name='Creado Por'),
        ),
    ]
